export const manualInventoryEntries = [
  { label: "Iglesia de Boada", slug: "iglesia-boada" },
  { label: "Reloj de Boada", slug: "torre-reloj-boada" },
  { label: "Casa de muñecas", slug: "casa-de-munecas" },
  { label: "Ventana de la iglesia de San Martín de Fuentidueña", slug: "ventana-san-martin-fuentiduena" },
  { label: "Ventana de la Universidad de Cusco", slug: "ventana-universidad-cusco" },
  { label: "Portada del Palacio de Anaya", slug: "fachada-palacio-anaya" },
  { label: "Ajedrez de pájaros", slug: "ajedrez-de-pajaros" },
  { label: "Castillo del Cubo", slug: "castillo-cubo-don-sancho" },
  { label: "Iglesia de San Muñoz", slug: "iglesia-san-munoz" },
  { label: "Portada de la capilla de la iglesia de Fuentidueña", slug: "portada-capilla-iglesia-fuentiduena" },
  { label: "Portada del convento de San Juan de Fuentidueña", slug: "portada-convento-san-juan-fuentiduena" },
  { label: "Caballito de madera", slug: "juguetilandia-de-alba" },
  { label: "Juguetilandia de Alba", slug: "juguetilandia-de-alba" },
  { label: "Portada de la Casa de los Maldonados", slug: "portada-casa-maldonados" },
  { label: "Antiguo Colegio de Huérfanos", slug: "colegio-huerfanos-salamanca" },
  { label: "Fachada renacentista de la iglesia de San Martín", slug: "fachada-iglesia-san-martin" },
  { label: "Fachada del Colegio del Arzobispo Fonseca", slug: "fachada-colegio-fonseca" },
  { label: "Fachada de la iglesia de Cuerva", slug: "fachada-iglesia-cuerva-toledo" },
  { label: "Fachada de la iglesia de San Pablo", slug: "portada-iglesia-san-pablo" },
  { label: "Portada románica de la iglesia de San Martín", slug: "puerta-romanica-san-martin" },
  { label: "Ventana lateral de la Casa de las Muertes", slug: "ventana-casa-de-las-muertes" },
  { label: "Ventana central de la Casa de las Muertes", slug: "ventana-casa-de-las-muertes" },
  { label: "Ventana de la iglesia del convento de las Clarisas", slug: "ventana-iglesia-convento-clarisas" },
  { label: "Portales de la Plaza de San Román", slug: "portico-iglesia-san-roman" },
  { label: "Juego de la rana", slug: "juego-de-la-rana" },
  { label: "Catedral de Ciudad Rodrigo", slug: "catedral-ciudad-rodrigo" },
  { label: "Patio de Escuelas Menores de Salamanca", slug: "patio-escuelas-menores-salamanca" },
  { label: "Torre de la Catedral Nueva de Salamanca", slug: "torre-catedral-nueva-salamanca" },
  { label: "Casa de las Conchas", slug: "casa-de-las-conchas" },
  { label: "Fachada de la Universidad de Salamanca", slug: "fachada-universidad-salamanca" },
  { label: "Ayuntamiento de Salamanca", slug: "ayuntamiento-salamanca" },
  { label: "Bueyes de San Isidro en Santa Olalla", slug: "bueyes-san-isidro-santa-olalla" },
  { label: "Torre del Clavero", slug: "torre-del-clavero-salamanca" },
  { label: "Iglesia de San Marcos", slug: "iglesia-san-marcos-salamanca" },
  { label: "Iglesia del Cubo de Don Sancho", slug: "iglesia-cubo-don-sancho" },
  { label: "Iglesia de Tamames", slug: "iglesia-tamames" },
  { label: "Belén", slug: "casitas-belen" },
  { label: "Ventana de la iglesia de Cristo Rey de Pasto", slug: "ventana-iglesia-cristo-rey-pasto" },
  { label: "Ventana de la iglesia de San Juan de Sahagún", slug: "ventana-iglesia-san-juan-de-sahagun" },
  { label: "Ventana del ábside de la iglesia de San Pelayo de Ayega", slug: "ventana-abside-iglesia-san-pelayo-de-ayega" },
  { label: "Maleta de madera - Belén", slug: "belen-maleta-madera" },
  { label: "Plaza Mayor de La Fuente de San Esteban", slug: "plaza-mayor-la-fuente-de-san-esteban" },
  { label: "Acueducto de Segovia", slug: "acueducto-de-segovia" },
  { label: "Iglesia de Ituero de Huebra", slug: "iglesia-ituero-de-huebra" },
  { label: "Iglesia de Santa Olalla de Yeltes", slug: "iglesia-santa-olalla-de-yeltes" },
  { label: "Iglesia de Villares de Yeltes", slug: "iglesia-villares-de-yeltes" },
  { label: "Ventana gótica del Palacio de Abrantes", slug: "ventana-palacio-de-abrantes" },
  { label: "Campanario de la iglesia vieja de los Pizarrales", slug: "campanario-iglesia-pizarrales" },
  { label: "Portada de la iglesia de San Miguel de Peñaranda de Bracamonte", slug: "portada-iglesia-san-miguel-penaranda-de-bracamonte" },
  { label: "Maleta de madera - Teatro", slug: "teatro-maleta-madera" },
  { label: "Fachada del convento de las Bernardas", slug: "portada-de-las-bernardas" },
  { label: "Ventana de la iglesia de San Miguel de Tubilla del Agua", slug: "ventana-iglesia-san-miguel-tubilla-del-agua" },
  { label: "Fachada de una casa de Monleón", slug: "fachada-casa-monleon" },
  { label: "Detalle - ventana con visillos", slug: "ventana-con-visillos" },
  { label: "Aperos de labranza", slug: "aperos-de-labranza" },
  { label: "Carro con bueyes", slug: "carro-con-bueyes" },
  { label: "Coches y motos antiguos", slug: "coches-y-motos-antiguos" },
  { label: "Desenjaule", slug: "desenjaule-toro-bravo" },
  { label: "Ayuntamiento de Ciudad Rodrigo", slug: "ayuntamiento-ciudad-rodrigo" },
  { label: "Antigua balconada de La Fuente", slug: "balconada-antigua-la-fuente-de-san-esteban" },
  { label: "Fachada de la Casa de Doña María la Brava", slug: "fachada-casa-dona-maria-la-brava" },
  { label: "Puerta de las Escuelas Menores", slug: "puerta-escuelas-menores-salamanca" },
  { label: "Portada de la iglesia de San Benito", slug: "portada-iglesia-san-benito-salamanca" },
  { label: "Maleta de madera - lago con cisnes", slug: "maleta-madera-lago" },
  { label: "Animales con piñas", slug: "animales-con-pinas" },
  { label: "Tres columnas de Ciudad Rodrigo", slug: "tres-columnas-ciudad-rodrigo" },
  { label: "Ermita de Nuestra Señora de los Remedios", slug: "ermita-nuestra-senora-remedios-buenamadre" },
  { label: "Portales de la iglesia de Jaramillo de la Fuente", slug: "portales-iglesia-jaramillo-de-la-fuente" },
  { label: "Ventana de la Casa de las Conchas", slug: "ventana-casa-de-las-conchas" },
  { label: "Revistero", slug: "muebles-y-utiles-de-madera" },
  { label: "Mesa de música", slug: "muebles-y-utiles-de-madera" },
  { label: "Ventana del santuario de Ta' Pinu", slug: "ventana-santuario-ta-pinu" },
  { label: "Fachada de casa de Pereña de la Ribera", slug: "fachada-casa-perena-de-la-ribera" },
  { label: "Juego de café", slug: "muebles-y-utiles-de-madera" },
  { label: "Platos y jarras", slug: "muebles-y-utiles-de-madera" },
];